server.port=8080
spring.application.name=cybershop-ctf

spring.datasource.url=jdbc:h2:mem:shopdb;INIT=CREATE SCHEMA IF NOT EXISTS CTF
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=false
spring.sql.init.mode=always

logging.level.org.apache.catalina.session=TRACE
logging.level.org.apache.catalina.session.ManagerBase=TRACE
logging.level.org.apache.catalina.session.StandardManager=TRACE

logging.level.org.springframework.transaction=TRACE
logging.level.org.springframework.jndi=TRACE