appname = public_disclosure
httpport = 8111
runmode = dev
copyrequestbody = true
EnableXSRF = true
XSRFKey = "sfim6moIyyuDN1tKbaEXNvwA2eX2sxe7wwjrEtMNOJo="
XSRFExpire = 3600

db_type = mysql
db_user = "28g7uo7XM1BNj1c.root"
db_pass = "FxCvYxQAZoanwx5s"
db_host = "gateway01.eu-central-1.prod.aws.tidbcloud.com"
db_port = 4000
db_name = "test"

sessionon = true
sessionname = "sessionid"
sessiongcmaxlifetime = 1800
sessioncookielifetime = 1800
sessioncookiehttponly = true
sessionsamesite = None
