
INSERT INTO users (username, password, role) VALUES ('admin', 'admin123', 'ADMIN');

INSERT INTO users (username, password, role) VALUES ('player', 'player123', 'USER');


INSERT INTO products (name, description, price, category, image_url, stock_quantity) VALUES ('Apple MacBook Pro 14 Inch Space Grey', 'The MacBook Pro 14 Inch in Space Grey is a powerful and sleek laptop, featuring Apple''s M1 Pro chip for exceptional performance and a stunning Retina display.', 1999.99, 'electronics', 'https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/thumbnail.webp', 24);
INSERT INTO products (name, description, price, category, image_url, stock_quantity) VALUES ('Asus Zenbook Pro Dual Screen Laptop', 'The Asus Zenbook Pro Dual Screen Laptop is a high-performance device with dual screens, providing productivity and versatility for creative professionals.', 1799.99, 'electronics', 'https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/thumbnail.webp', 45);
INSERT INTO products (name, description, price, category, image_url, stock_quantity) VALUES ('Huawei Matebook X Pro', 'The Huawei Matebook X Pro is a slim and stylish laptop with a high-resolution touchscreen display, offering a premium experience for users on the go.', 1399.99, 'electronics', 'https://cdn.dummyjson.com/product-images/laptops/huawei-matebook-x-pro/thumbnail.webp', 75);
INSERT INTO products (name, description, price, category, image_url, stock_quantity) VALUES ('Lenovo Yoga 920', 'The Lenovo Yoga 920 is a 2-in-1 convertible laptop with a flexible hinge, allowing you to use it as a laptop or tablet, offering versatility and portability.', 1099.99, 'electronics', 'https://cdn.dummyjson.com/product-images/laptops/lenovo-yoga-920/thumbnail.webp', 40);
INSERT INTO products (name, description, price, category, image_url, stock_quantity) VALUES ('New DELL XPS 13 9300 Laptop', 'The New DELL XPS 13 9300 Laptop is a compact and powerful device, featuring a virtually borderless InfinityEdge display and high-end performance for various tasks.', 1499.99, 'electronics', 'https://cdn.dummyjson.com/product-images/laptops/new-dell-xps-13-9300-laptop/thumbnail.webp', 74);
INSERT INTO products (name, description, price, category, image_url, stock_quantity) VALUES ('iPhone 5s', 'The iPhone 5s is a classic smartphone known for its compact design and advanced features during its release. While it''s an older model, it still provides a reliable user experience.', 199.99, 'electronics', 'https://cdn.dummyjson.com/product-images/smartphones/iphone-5s/thumbnail.webp', 25);
INSERT INTO products (name, description, price, category, image_url, stock_quantity) VALUES ('iPhone 6', 'The iPhone 6 is a stylish and capable smartphone with a larger display and improved performance. It introduced new features and design elements, making it a popular choice in its time.', 299.99, 'electronics', 'https://cdn.dummyjson.com/product-images/smartphones/iphone-6/thumbnail.webp', 60);
INSERT INTO products (name, description, price, category, image_url, stock_quantity) VALUES ('iPhone 13 Pro', 'The iPhone 13 Pro is a cutting-edge smartphone with a powerful camera system, high-performance chip, and stunning display. It offers advanced features for users who demand top-notch technology.', 1099.99, 'electronics', 'https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/thumbnail.webp', 56);
INSERT INTO products (name, description, price, category, image_url, stock_quantity) VALUES ('iPhone X', 'The iPhone X is a flagship smartphone featuring a bezel-less OLED display, facial recognition technology (Face ID), and impressive performance. It represents a milestone in iPhone design and innovation.', 899.99, 'electronics', 'https://cdn.dummyjson.com/product-images/smartphones/iphone-x/thumbnail.webp', 37);
INSERT INTO products (name, description, price, category, image_url, stock_quantity) VALUES ('Oppo A57', 'The Oppo A57 is a mid-range smartphone known for its sleek design and capable features. It offers a balance of performance and affordability, making it a popular choice.', 249.99, 'electronics', 'https://cdn.dummyjson.com/product-images/smartphones/oppo-a57/thumbnail.webp', 19);
INSERT INTO products (name, description, price, category, image_url, stock_quantity) VALUES ('Amazon Echo Plus', 'The Amazon Echo Plus is a smart speaker with built-in Alexa voice control. It features premium sound quality and serves as a hub for controlling smart home devices.', 99.99, 'accessories', 'https://cdn.dummyjson.com/product-images/mobile-accessories/amazon-echo-plus/thumbnail.webp', 61);
INSERT INTO products (name, description, price, category, image_url, stock_quantity) VALUES ('Apple Airpods', 'The Apple Airpods offer a seamless wireless audio experience. With easy pairing, high-quality sound, and Siri integration, they are perfect for on-the-go listening.', 129.99, 'accessories', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods/thumbnail.webp', 67);
INSERT INTO products (name, description, price, category, image_url, stock_quantity) VALUES ('Apple AirPods Max Silver', 'The Apple AirPods Max in Silver are premium over-ear headphones with high-fidelity audio, adaptive EQ, and active noise cancellation. Experience immersive sound in style.', 549.99, 'accessories', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods-max-silver/thumbnail.webp', 59);
INSERT INTO products (name, description, price, category, image_url, stock_quantity) VALUES ('Apple Airpower Wireless Charger', 'The Apple AirPower Wireless Charger provides a convenient way to charge your compatible Apple devices wirelessly. Simply place your devices on the charging mat for effortless charging.', 79.99, 'accessories', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpower-wireless-charger/thumbnail.webp', 1);
INSERT INTO products (name, description, price, category, image_url, stock_quantity) VALUES ('Apple HomePod Mini Cosmic Grey', 'The Apple HomePod Mini in Cosmic Grey is a compact smart speaker that delivers impressive audio and integrates seamlessly with the Apple ecosystem for a smart home experience.', 99.99, 'accessories', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-homepod-mini-cosmic-grey/thumbnail.webp', 27);
INSERT INTO products (name, description, price, category, image_url, stock_quantity) VALUES ('Apple iPhone Charger', 'The Apple iPhone Charger is a high-quality charger designed for fast and efficient charging of your iPhone. Ensure your device stays powered up and ready to go.', 19.99, 'accessories', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/thumbnail.webp', 31);
INSERT INTO products (name, description, price, category, image_url, stock_quantity) VALUES ('Apple MagSafe Battery Pack', 'The Apple MagSafe Battery Pack is a portable and convenient way to add extra battery life to your MagSafe-compatible iPhone. Attach it magnetically for a secure connection.', 99.99, 'accessories', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-magsafe-battery-pack/thumbnail.webp', 1);
INSERT INTO products (name, description, price, category, image_url, stock_quantity) VALUES ('Apple Watch Series 4 Gold', 'The Apple Watch Series 4 in Gold is a stylish and advanced smartwatch with features like heart rate monitoring, fitness tracking, and a beautiful Retina display.', 349.99, 'accessories', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-watch-series-4-gold/thumbnail.webp', 33);
INSERT INTO products (name, description, price, category, image_url, stock_quantity) VALUES ('Beats Flex Wireless Earphones', 'The Beats Flex Wireless Earphones offer a comfortable and versatile audio experience. With magnetic earbuds and up to 12 hours of battery life, they are ideal for everyday use.', 49.99, 'accessories', 'https://cdn.dummyjson.com/product-images/mobile-accessories/beats-flex-wireless-earphones/thumbnail.webp', 50);
INSERT INTO products (name, description, price, category, image_url, stock_quantity) VALUES ('iPhone 12 Silicone Case with MagSafe Plum', 'The iPhone 12 Silicone Case with MagSafe in Plum is a stylish and protective case designed for the iPhone 12. It features MagSafe technology for easy attachment of accessories.', 29.99, 'accessories', 'https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/thumbnail.webp', 69);
INSERT INTO products (name, description, price, category, image_url, stock_quantity) VALUES ('WD 2TB Elements Portable External Hard Drive - USB 3.0 ', 'USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user’s hardware configuration and operating system', 64, 'peripherals', 'https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg', 50);
INSERT INTO products (name, description, price, category, image_url, stock_quantity) VALUES ('SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s', 'Easy upgrade for faster boot up, shutdown, application load and response Boosts burst write performance, making it ideal for typical PC workloads The perfect balance of performance and reliability Read/write speeds of up to 535MB/s/450MB/s', 109, 'peripherals', 'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg', 50);
INSERT INTO products (name, description, price, category, image_url, stock_quantity) VALUES ('Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5', '3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance. The advanced SLC Cache Technology allows performance boost and longer lifespan', 109, 'peripherals', 'https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg', 50);
INSERT INTO products (name, description, price, category, image_url, stock_quantity) VALUES ('WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive', 'Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year manufacturer''s limited warranty', 114, 'peripherals', 'https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg', 50);
INSERT INTO products (name, description, price, category, image_url, stock_quantity) VALUES ('Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin', '21. 5 inches Full HD (1920 x 1080) widescreen IPS display And Radeon free Sync technology. Refresh Rate: 75Hz - Using HDMI port Zero-frame design | ultra-thin', 599, 'peripherals', 'https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg', 50);
INSERT INTO products (name, description, price, category, image_url, stock_quantity) VALUES ('Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor', '49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MONITOR with dual 27 inch screen side by side QUANTUM DOT (QLED) TECHNOLOGY, HDR support and factory calibration', 999.99, 'peripherals', 'https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg', 50);
INSERT INTO products (name, description, price, category, image_url, stock_quantity) VALUES ('Apple AirPods Max Silver (Perip)', 'The Apple AirPods Max in Silver are premium over-ear headphones with high-fidelity audio, adaptive EQ, and active noise cancellation. Experience immersive sound in style.', 549.99, 'peripherals', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods-max-silver/thumbnail.webp', 59);
INSERT INTO products (name, description, price, category, image_url, stock_quantity) VALUES ('Apple AirPods Pro', 'Magic like you’ve never heard. Bose products are known for their sound quality. We like to think of them as the best in the business.', 249.99, 'peripherals', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods/thumbnail.webp', 67);
INSERT INTO products (name, description, price, category, image_url, stock_quantity) VALUES ('Logitech G Pro Mouse', 'High speed, high quality gaming mouse for pros.', 129.99, 'peripherals', 'https://via.placeholder.com/150?text=Mouse', 40);
INSERT INTO products (name, description, price, category, image_url, stock_quantity) VALUES ('Mechanical Keyboard RGB', 'Tactile switch mechanical keyboard with RGB.', 149.99, 'peripherals', 'https://via.placeholder.com/150?text=Keyboard', 50);


INSERT INTO promo_codes (code, discount_percentage, is_active, user_id) VALUES ('CYBERSHOP-WELCOME-2026', 10, TRUE, NULL);
INSERT INTO promo_codes (code, discount_percentage, is_active, user_id) VALUES ('CYBERSHOP-SUMMER-50', 50, TRUE, NULL);


INSERT INTO orders (user_id, status, total_price, created_at) VALUES (2, 'PENDING', 3799.98, CURRENT_TIMESTAMP);
INSERT INTO order_items (order_id, product_id, quantity, price) VALUES (1, 1, 1, 1999.99);
INSERT INTO order_items (order_id, product_id, quantity, price) VALUES (1, 2, 1, 1799.99);

